
name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby: ["4.0", "head"]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: rm -f Gemfile.lock
      - run: rm -f .ruby-version
      - name: Set up Ruby
        uses: ruby/setup-ruby@28c65f7bd3231513f1560eb7d7ec44501e65d10b # v1.309.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler: latest
          bundler-cache: true

      - run: bundle exec rspec
